name: 'Manage PR Description'
description: 'Create or update a PR description with a unique ID'
author: 'zouwu.fr'

inputs:
  github-token:
    description: 'GitHub token for API authentication'
    required: true
  section-id:
    description: 'Unique identifier for the section (e.g., "pr-environment")'
    required: true
  content:
    description: 'The content to insert between the tags (markdown supported)'
    required: true
  pr-number:
    description: 'The PR number (optional, auto-detected if not provided)'
    required: false

outputs:
  updated:
    description: 'Whether the section was updated (true) or created (false)'
    value: ${{ steps.update-pr.outputs.updated }}

runs:
  using: 'composite'
  steps:
    - name: Get PR Number
      id: pr-number
      shell: bash
      run: |
        if [ -n "${{ inputs.pr-number }}" ]; then
          echo "number=${{ inputs.pr-number }}" >> $GITHUB_OUTPUT
        else
          PR_NUM="${{ github.event.pull_request.number }}"
          if [ -z "$PR_NUM" ] || [ "$PR_NUM" = "null" ]; then
            echo "::error::Could not determine PR number. Make sure this action runs in a pull_request context or provide pr-number input."
            exit 1
          fi
          echo "number=$PR_NUM" >> $GITHUB_OUTPUT
        fi

    - name: Update PR description
      id: update-pr
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ steps.pr-number.outputs.number }}
        SECTION_ID: ${{ inputs.section-id }}
        CONTENT: ${{ inputs.content }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const prNumber = parseInt(process.env.PR_NUMBER, 10);
          const sectionId = process.env.SECTION_ID;
          const newContent = process.env.CONTENT;

          // Define the header and section markers
          const headerMarker = '<!-- This is an auto-generated comment: created by zouwu.fr -->';
          const startMarker = `<!-- ${sectionId} -->`;
          const endMarker = `<!-- end: ${sectionId} -->`;

          console.log(`📝 Processing PR #${prNumber} with section ID: ${sectionId}`);

          // Get current PR description
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          });

          let currentBody = pr.body || '';
          
          // Build the new section
          const newSection = `${startMarker}\n${newContent}\n${endMarker}`;

          let updatedBody;
          let wasUpdated = false;

          // Check if section already exists
          const startIndex = currentBody.indexOf(startMarker);
          const endIndex = currentBody.indexOf(endMarker);

          if (startIndex !== -1 && endIndex !== -1) {
            // Replace existing section
            console.log(`🔄 Updating existing section: ${sectionId}`);
            updatedBody = currentBody.substring(0, startIndex) +
                          newSection +
                          currentBody.substring(endIndex + endMarker.length);
            wasUpdated = true;
          } else {
            // Add new section
            console.log(`➕ Adding new section: ${sectionId}`);
          
            // Check if header exists
            if (!currentBody.includes(headerMarker)) {
              // Add header if this is the first auto-generated section
              if (currentBody.trim()) {
                updatedBody = `${currentBody.trim()}\n\n---\n\n${headerMarker}\n\n${newSection}`;
              } else {
                updatedBody = `${headerMarker}\n\n${newSection}`;
              }
            } else {
              // Header exists, just append the new section
              updatedBody = `${currentBody.trim()}\n\n${newSection}`;
            }
            wasUpdated = false;
          }

          // Update the PR
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            body: updatedBody
          });

          core.setOutput('updated', wasUpdated);
          console.log(`✅ Successfully ${wasUpdated ? 'updated' : 'created'} section in PR #${prNumber}`);

branding:
  icon: 'message-square'
  color: 'blue'